// Auto-generated by deploy script — do not edit manually
// Network: sepolia | Deployed: 2026-03-22T11:42:25.603Z

export const CONTRACT_ADDRESS = "0xdFC60484EEa7f91ebeC689fDA8C15c137a492c2a" as const;
export const CHAIN_ID = 11155111;
export const NETWORK = "sepolia";

// Validator IDs (keccak256 of name string, matching on-chain registration)
export const VALIDATOR_IDS = {
  "Alpha": "0x4c23426613a5dc69e08fbd2787e6210aa679d4522e95a89d4dd88c4fd13a2283" as const,
  "Beta": "0x23d235efaf569b2b407d10f447247743508d1762a8e3a3aed85ccc0570dde35f" as const,
  "Gamma": "0x4ade54ca82b345967b61d43a7b6e1c256d140cceb65202e7117104371c17959c" as const,
  "Delta": "0x936a052e832d05db833c1fb152ee9d04cb963f54db694a4cc58e037932bdbf61" as const,
  "Epsilon": "0x81685035bf6e9d5f45bbedb20e2e5ca3f52663efad8040454930d989b0bd1f49" as const,
  "Zeta": "0xc1f3458591aa5dbadd866836ff54b5edb079a2e1de0432c95a85f45437b12bfe" as const,
} as const;

// AVS IDs
export const AVS_IDS = {
  "EigenDA": "0xaaf21b8fe9604d106ac0fca70c8d0c3456560fb48834a2a5677dcfad64e8a95e" as const,
  "Lagrange": "0x5821ef190e50e888edaecb19c2dde89a0f48b76e045d5abd44c63c9739f5d656" as const,
  "Omni Network": "0xf140ed84d0729d5c230cf4f38eb6a6ec655df75f3cb12314dc78e9cb76c4ed66" as const,
  "AltLayer": "0x15751b7a63c0d5f75a75e06d8c836dd9d710facd29b7acb0a22b6c58cbc45e3f" as const,
  "Witness Chain": "0x514536057e51d838269a79c5f45cedb3152aa2faaebe19add1c49184731cfa3d" as const,
} as const;
