import type { Validator, AVSService } from "@/app/types";

export const INITIAL_VALIDATORS: Validator[] = [
  {
    id: "V1",
    name: "Validator Alpha",
    stake: 4800,
    color: "#4fc3f7",
    services: ["AVS-A", "AVS-B", "AVS-C"],
    x: 0, y: 0,
    slashedStake: 0,
    status: "normal",
  },
  {
    id: "V2",
    name: "Validator Beta",
    stake: 3200,
    color: "#81c784",
    services: ["AVS-A", "AVS-D"],
    x: 0, y: 0,
    slashedStake: 0,
    status: "normal",
  },
  {
    id: "V3",
    name: "Validator Gamma",
    stake: 2900,
    color: "#ba68c8",
    services: ["AVS-B", "AVS-C"],
    x: 0, y: 0,
    slashedStake: 0,
    status: "normal",
  },
  {
    id: "V4",
    name: "Validator Delta",
    stake: 1800,
    color: "#ff8a65",
    services: ["AVS-C", "AVS-D"],
    x: 0, y: 0,
    slashedStake: 0,
    status: "normal",
  },
  {
    id: "V5",
    name: "Validator Epsilon",
    stake: 3600,
    color: "#4db6ac",
    services: ["AVS-A", "AVS-B", "AVS-D", "AVS-E"],
    x: 0, y: 0,
    slashedStake: 0,
    status: "normal",
  },
  {
    id: "V6",
    name: "Validator Zeta",
    stake: 1400,
    color: "#f06292",
    services: ["AVS-E"],
    x: 0, y: 0,
    slashedStake: 0,
    status: "normal",
  },
];

export const INITIAL_AVS_SERVICES: AVSService[] = [
  {
    id: "AVS-A",
    name: "EigenDA",
    tvl: 8500,
    rewardAPY: 4.2,
    color: "#4fc3f7",
    status: "normal",
    x: 0, y: 0,
    description: "Data availability layer for rollups. High connectivity makes it the highest-risk attack surface.",
  },
  {
    id: "AVS-B",
    name: "Lagrange",
    tvl: 6200,
    rewardAPY: 3.8,
    color: "#81c784",
    status: "normal",
    x: 0, y: 0,
    description: "ZK coprocessor network providing verifiable off-chain compute to smart contracts.",
  },
  {
    id: "AVS-C",
    name: "Omni Network",
    tvl: 5100,
    rewardAPY: 5.1,
    color: "#ba68c8",
    status: "normal",
    x: 0, y: 0,
    description: "Cross-rollup messaging layer. Failure here disrupts interoperability across L2 ecosystem.",
  },
  {
    id: "AVS-D",
    name: "AltLayer",
    tvl: 4300,
    rewardAPY: 3.3,
    color: "#ff8a65",
    status: "normal",
    x: 0, y: 0,
    description: "Restaked rollup service providing decentralized sequencing and settlement.",
  },
  {
    id: "AVS-E",
    name: "Witness Chain",
    tvl: 3900,
    rewardAPY: 6.0,
    color: "#4db6ac",
    status: "normal",
    x: 0, y: 0,
    description: "Decentralized watchtower network. Isolated validator base limits cascade risk.",
  },
];
