/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRestakingGuard__factory } from "./IRestakingGuard__factory";
export { RestakingGuard__factory } from "./RestakingGuard__factory";
