/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRestakingGuard,
  IRestakingGuardInterface,
} from "../IRestakingGuard";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "AVSAlreadyByzantine",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "AVSAlreadyRegistered",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "AVSNotFound",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "AlreadyAllocated",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientStake",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "NotAllocated",
    type: "error",
  },
  {
    inputs: [],
    name: "Unauthorized",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
    ],
    name: "ValidatorAlreadyRegistered",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "ValidatorAlreadySlashed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
    ],
    name: "ValidatorNotFound",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "reporter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "AVSFlaggedByzantine",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "AVSRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "slashedValidatorCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalValidatorCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "CascadeRiskDetected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "newScore",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalSlashed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RiskScoreUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "ValidatorAllocated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "ValidatorDeallocated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stake",
        type: "uint256",
      },
    ],
    name: "ValidatorRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "byzantineAvsId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "slashedAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ValidatorSlashed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "allocateValidator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "deallocateValidator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "slashBps",
        type: "uint256",
      },
    ],
    name: "executeSlashing",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "getAVS",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "avsId",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "totalTVL",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "validatorCount",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "slashedCount",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "byzantine",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
        ],
        internalType: "struct IRestakingGuard.AVSInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "getAVSValidators",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "getCascadeRisk",
    outputs: [
      {
        internalType: "uint256",
        name: "riskBps",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNetworkRiskScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
    ],
    name: "getValidator",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "validatorId",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "totalStake",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "slashedStake",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "serviceCount",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
        ],
        internalType: "struct IRestakingGuard.ValidatorInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
    ],
    name: "getValidatorServices",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "isAllocated",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "tvl",
        type: "uint256",
      },
    ],
    name: "registerAVS",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "validatorId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "stake",
        type: "uint256",
      },
    ],
    name: "registerValidator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "reportByzantine",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRestakingGuard__factory {
  static readonly abi = _abi;
  static createInterface(): IRestakingGuardInterface {
    return new Interface(_abi) as IRestakingGuardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRestakingGuard {
    return new Contract(address, _abi, runner) as unknown as IRestakingGuard;
  }
}
