/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IRestakingGuard {
  export type AVSInfoStruct = {
    avsId: BytesLike;
    name: string;
    totalTVL: BigNumberish;
    validatorCount: BigNumberish;
    slashedCount: BigNumberish;
    byzantine: boolean;
    active: boolean;
  };

  export type AVSInfoStructOutput = [
    avsId: string,
    name: string,
    totalTVL: bigint,
    validatorCount: bigint,
    slashedCount: bigint,
    byzantine: boolean,
    active: boolean
  ] & {
    avsId: string;
    name: string;
    totalTVL: bigint;
    validatorCount: bigint;
    slashedCount: bigint;
    byzantine: boolean;
    active: boolean;
  };

  export type ValidatorInfoStruct = {
    validatorId: BytesLike;
    totalStake: BigNumberish;
    slashedStake: BigNumberish;
    serviceCount: BigNumberish;
    active: boolean;
  };

  export type ValidatorInfoStructOutput = [
    validatorId: string,
    totalStake: bigint,
    slashedStake: bigint,
    serviceCount: bigint,
    active: boolean
  ] & {
    validatorId: string;
    totalStake: bigint;
    slashedStake: bigint;
    serviceCount: bigint;
    active: boolean;
  };
}

export interface IRestakingGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allocateValidator"
      | "deallocateValidator"
      | "executeSlashing"
      | "getAVS"
      | "getAVSValidators"
      | "getCascadeRisk"
      | "getNetworkRiskScore"
      | "getValidator"
      | "getValidatorServices"
      | "isAllocated"
      | "registerAVS"
      | "registerValidator"
      | "reportByzantine"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AVSFlaggedByzantine"
      | "AVSRegistered"
      | "CascadeRiskDetected"
      | "RiskScoreUpdated"
      | "ValidatorAllocated"
      | "ValidatorDeallocated"
      | "ValidatorRegistered"
      | "ValidatorSlashed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allocateValidator",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deallocateValidator",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSlashing",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAVS", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAVSValidators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCascadeRisk",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorServices",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllocated",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAVS",
    values: [BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerValidator",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reportByzantine",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allocateValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deallocateValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSlashing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAVS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAVSValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCascadeRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllocated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportByzantine",
    data: BytesLike
  ): Result;
}

export namespace AVSFlaggedByzantineEvent {
  export type InputTuple = [
    avsId: BytesLike,
    reporter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    avsId: string,
    reporter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    avsId: string;
    reporter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AVSRegisteredEvent {
  export type InputTuple = [avsId: BytesLike, name: string];
  export type OutputTuple = [avsId: string, name: string];
  export interface OutputObject {
    avsId: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CascadeRiskDetectedEvent {
  export type InputTuple = [
    avsId: BytesLike,
    slashedValidatorCount: BigNumberish,
    totalValidatorCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    avsId: string,
    slashedValidatorCount: bigint,
    totalValidatorCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    avsId: string;
    slashedValidatorCount: bigint;
    totalValidatorCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreUpdatedEvent {
  export type InputTuple = [
    newScore: BigNumberish,
    totalSlashed: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    newScore: bigint,
    totalSlashed: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    newScore: bigint;
    totalSlashed: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorAllocatedEvent {
  export type InputTuple = [validatorId: BytesLike, avsId: BytesLike];
  export type OutputTuple = [validatorId: string, avsId: string];
  export interface OutputObject {
    validatorId: string;
    avsId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorDeallocatedEvent {
  export type InputTuple = [validatorId: BytesLike, avsId: BytesLike];
  export type OutputTuple = [validatorId: string, avsId: string];
  export interface OutputObject {
    validatorId: string;
    avsId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRegisteredEvent {
  export type InputTuple = [validatorId: BytesLike, stake: BigNumberish];
  export type OutputTuple = [validatorId: string, stake: bigint];
  export interface OutputObject {
    validatorId: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorSlashedEvent {
  export type InputTuple = [
    validatorId: BytesLike,
    byzantineAvsId: BytesLike,
    slashedAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    validatorId: string,
    byzantineAvsId: string,
    slashedAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    validatorId: string;
    byzantineAvsId: string;
    slashedAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRestakingGuard extends BaseContract {
  connect(runner?: ContractRunner | null): IRestakingGuard;
  waitForDeployment(): Promise<this>;

  interface: IRestakingGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allocateValidator: TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;

  deallocateValidator: TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;

  executeSlashing: TypedContractMethod<
    [avsId: BytesLike, slashBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAVS: TypedContractMethod<
    [avsId: BytesLike],
    [IRestakingGuard.AVSInfoStructOutput],
    "view"
  >;

  getAVSValidators: TypedContractMethod<[avsId: BytesLike], [string[]], "view">;

  getCascadeRisk: TypedContractMethod<[avsId: BytesLike], [bigint], "view">;

  getNetworkRiskScore: TypedContractMethod<[], [bigint], "view">;

  getValidator: TypedContractMethod<
    [validatorId: BytesLike],
    [IRestakingGuard.ValidatorInfoStructOutput],
    "view"
  >;

  getValidatorServices: TypedContractMethod<
    [validatorId: BytesLike],
    [string[]],
    "view"
  >;

  isAllocated: TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [boolean],
    "view"
  >;

  registerAVS: TypedContractMethod<
    [avsId: BytesLike, name: string, tvl: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerValidator: TypedContractMethod<
    [validatorId: BytesLike, stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  reportByzantine: TypedContractMethod<
    [avsId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allocateValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deallocateValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSlashing"
  ): TypedContractMethod<
    [avsId: BytesLike, slashBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAVS"
  ): TypedContractMethod<
    [avsId: BytesLike],
    [IRestakingGuard.AVSInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAVSValidators"
  ): TypedContractMethod<[avsId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCascadeRisk"
  ): TypedContractMethod<[avsId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNetworkRiskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike],
    [IRestakingGuard.ValidatorInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorServices"
  ): TypedContractMethod<[validatorId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isAllocated"
  ): TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAVS"
  ): TypedContractMethod<
    [avsId: BytesLike, name: string, tvl: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike, stake: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportByzantine"
  ): TypedContractMethod<[avsId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AVSFlaggedByzantine"
  ): TypedContractEvent<
    AVSFlaggedByzantineEvent.InputTuple,
    AVSFlaggedByzantineEvent.OutputTuple,
    AVSFlaggedByzantineEvent.OutputObject
  >;
  getEvent(
    key: "AVSRegistered"
  ): TypedContractEvent<
    AVSRegisteredEvent.InputTuple,
    AVSRegisteredEvent.OutputTuple,
    AVSRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CascadeRiskDetected"
  ): TypedContractEvent<
    CascadeRiskDetectedEvent.InputTuple,
    CascadeRiskDetectedEvent.OutputTuple,
    CascadeRiskDetectedEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreUpdated"
  ): TypedContractEvent<
    RiskScoreUpdatedEvent.InputTuple,
    RiskScoreUpdatedEvent.OutputTuple,
    RiskScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorAllocated"
  ): TypedContractEvent<
    ValidatorAllocatedEvent.InputTuple,
    ValidatorAllocatedEvent.OutputTuple,
    ValidatorAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorDeallocated"
  ): TypedContractEvent<
    ValidatorDeallocatedEvent.InputTuple,
    ValidatorDeallocatedEvent.OutputTuple,
    ValidatorDeallocatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRegistered"
  ): TypedContractEvent<
    ValidatorRegisteredEvent.InputTuple,
    ValidatorRegisteredEvent.OutputTuple,
    ValidatorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorSlashed"
  ): TypedContractEvent<
    ValidatorSlashedEvent.InputTuple,
    ValidatorSlashedEvent.OutputTuple,
    ValidatorSlashedEvent.OutputObject
  >;

  filters: {
    "AVSFlaggedByzantine(bytes32,address,uint256)": TypedContractEvent<
      AVSFlaggedByzantineEvent.InputTuple,
      AVSFlaggedByzantineEvent.OutputTuple,
      AVSFlaggedByzantineEvent.OutputObject
    >;
    AVSFlaggedByzantine: TypedContractEvent<
      AVSFlaggedByzantineEvent.InputTuple,
      AVSFlaggedByzantineEvent.OutputTuple,
      AVSFlaggedByzantineEvent.OutputObject
    >;

    "AVSRegistered(bytes32,string)": TypedContractEvent<
      AVSRegisteredEvent.InputTuple,
      AVSRegisteredEvent.OutputTuple,
      AVSRegisteredEvent.OutputObject
    >;
    AVSRegistered: TypedContractEvent<
      AVSRegisteredEvent.InputTuple,
      AVSRegisteredEvent.OutputTuple,
      AVSRegisteredEvent.OutputObject
    >;

    "CascadeRiskDetected(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      CascadeRiskDetectedEvent.InputTuple,
      CascadeRiskDetectedEvent.OutputTuple,
      CascadeRiskDetectedEvent.OutputObject
    >;
    CascadeRiskDetected: TypedContractEvent<
      CascadeRiskDetectedEvent.InputTuple,
      CascadeRiskDetectedEvent.OutputTuple,
      CascadeRiskDetectedEvent.OutputObject
    >;

    "RiskScoreUpdated(uint256,uint256,uint256)": TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;
    RiskScoreUpdated: TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;

    "ValidatorAllocated(bytes32,bytes32)": TypedContractEvent<
      ValidatorAllocatedEvent.InputTuple,
      ValidatorAllocatedEvent.OutputTuple,
      ValidatorAllocatedEvent.OutputObject
    >;
    ValidatorAllocated: TypedContractEvent<
      ValidatorAllocatedEvent.InputTuple,
      ValidatorAllocatedEvent.OutputTuple,
      ValidatorAllocatedEvent.OutputObject
    >;

    "ValidatorDeallocated(bytes32,bytes32)": TypedContractEvent<
      ValidatorDeallocatedEvent.InputTuple,
      ValidatorDeallocatedEvent.OutputTuple,
      ValidatorDeallocatedEvent.OutputObject
    >;
    ValidatorDeallocated: TypedContractEvent<
      ValidatorDeallocatedEvent.InputTuple,
      ValidatorDeallocatedEvent.OutputTuple,
      ValidatorDeallocatedEvent.OutputObject
    >;

    "ValidatorRegistered(bytes32,uint256)": TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;
    ValidatorRegistered: TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;

    "ValidatorSlashed(bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;
    ValidatorSlashed: TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;
  };
}
