/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RestakingGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "CASCADE_RISK_WEIGHT"
      | "CASCADE_THRESHOLD_BPS"
      | "MAX_SLASH_BPS"
      | "PRIMARY_RISK_WEIGHT"
      | "allAvsIds"
      | "allValidatorIds"
      | "allocateValidator"
      | "avsCount"
      | "deallocateValidator"
      | "executeSlashing"
      | "getAVS"
      | "getAVSValidators"
      | "getAllAvsIds"
      | "getAllValidatorIds"
      | "getCascadeRisk"
      | "getNetworkRiskScore"
      | "getNetworkSnapshot"
      | "getValidator"
      | "getValidatorServices"
      | "isAllocated"
      | "networkRiskScore"
      | "owner"
      | "registerAVS"
      | "registerValidator"
      | "reportByzantine"
      | "totalNetworkStake"
      | "totalSlashedStake"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AVSFlaggedByzantine"
      | "AVSRegistered"
      | "CascadeRiskDetected"
      | "OwnershipTransferred"
      | "RiskScoreUpdated"
      | "ValidatorAllocated"
      | "ValidatorDeallocated"
      | "ValidatorRegistered"
      | "ValidatorSlashed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CASCADE_RISK_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CASCADE_THRESHOLD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SLASH_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIMARY_RISK_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allAvsIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allValidatorIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allocateValidator",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "avsCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deallocateValidator",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSlashing",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAVS", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAVSValidators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAvsIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllValidatorIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCascadeRisk",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorServices",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllocated",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "networkRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAVS",
    values: [BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerValidator",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reportByzantine",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalNetworkStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSlashedStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CASCADE_RISK_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CASCADE_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SLASH_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIMARY_RISK_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allAvsIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allValidatorIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "avsCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deallocateValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSlashing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAVS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAVSValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAvsIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllValidatorIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCascadeRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllocated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "networkRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportByzantine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalNetworkStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSlashedStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AVSFlaggedByzantineEvent {
  export type InputTuple = [
    avsId: BytesLike,
    reporter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    avsId: string,
    reporter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    avsId: string;
    reporter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AVSRegisteredEvent {
  export type InputTuple = [avsId: BytesLike, name: string, tvl: BigNumberish];
  export type OutputTuple = [avsId: string, name: string, tvl: bigint];
  export interface OutputObject {
    avsId: string;
    name: string;
    tvl: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CascadeRiskDetectedEvent {
  export type InputTuple = [
    secondaryAvsId: BytesLike,
    slashedCount: BigNumberish,
    totalCount: BigNumberish,
    riskBps: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    secondaryAvsId: string,
    slashedCount: bigint,
    totalCount: bigint,
    riskBps: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    secondaryAvsId: string;
    slashedCount: bigint;
    totalCount: bigint;
    riskBps: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreUpdatedEvent {
  export type InputTuple = [
    newScore: BigNumberish,
    totalSlashedStake: BigNumberish,
    totalNetworkStake: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    newScore: bigint,
    totalSlashedStake: bigint,
    totalNetworkStake: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    newScore: bigint;
    totalSlashedStake: bigint;
    totalNetworkStake: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorAllocatedEvent {
  export type InputTuple = [validatorId: BytesLike, avsId: BytesLike];
  export type OutputTuple = [validatorId: string, avsId: string];
  export interface OutputObject {
    validatorId: string;
    avsId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorDeallocatedEvent {
  export type InputTuple = [validatorId: BytesLike, avsId: BytesLike];
  export type OutputTuple = [validatorId: string, avsId: string];
  export interface OutputObject {
    validatorId: string;
    avsId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRegisteredEvent {
  export type InputTuple = [validatorId: BytesLike, stake: BigNumberish];
  export type OutputTuple = [validatorId: string, stake: bigint];
  export interface OutputObject {
    validatorId: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorSlashedEvent {
  export type InputTuple = [
    validatorId: BytesLike,
    byzantineAvsId: BytesLike,
    slashedAmount: BigNumberish,
    remainingStake: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    validatorId: string,
    byzantineAvsId: string,
    slashedAmount: bigint,
    remainingStake: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    validatorId: string;
    byzantineAvsId: string;
    slashedAmount: bigint;
    remainingStake: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RestakingGuard extends BaseContract {
  connect(runner?: ContractRunner | null): RestakingGuard;
  waitForDeployment(): Promise<this>;

  interface: RestakingGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  CASCADE_RISK_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  CASCADE_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_SLASH_BPS: TypedContractMethod<[], [bigint], "view">;

  PRIMARY_RISK_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  allAvsIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allValidatorIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allocateValidator: TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;

  avsCount: TypedContractMethod<[], [bigint], "view">;

  deallocateValidator: TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;

  executeSlashing: TypedContractMethod<
    [avsId: BytesLike, slashBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAVS: TypedContractMethod<
    [avsId: BytesLike],
    [
      [string, bigint, bigint, boolean, boolean, boolean] & {
        name: string;
        totalTVL: bigint;
        validatorCount: bigint;
        byzantine: boolean;
        cascadeRisk: boolean;
        active: boolean;
      }
    ],
    "view"
  >;

  getAVSValidators: TypedContractMethod<[avsId: BytesLike], [string[]], "view">;

  getAllAvsIds: TypedContractMethod<[], [string[]], "view">;

  getAllValidatorIds: TypedContractMethod<[], [string[]], "view">;

  getCascadeRisk: TypedContractMethod<[avsId: BytesLike], [bigint], "view">;

  getNetworkRiskScore: TypedContractMethod<[], [bigint], "view">;

  getNetworkSnapshot: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _totalNetworkStake: bigint;
        _totalSlashedStake: bigint;
        _networkRiskScore: bigint;
        _validatorCount: bigint;
        _avsCount: bigint;
      }
    ],
    "view"
  >;

  getValidator: TypedContractMethod<
    [validatorId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalStake: bigint;
        slashedStake: bigint;
        remainingStake: bigint;
        serviceCount: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getValidatorServices: TypedContractMethod<
    [validatorId: BytesLike],
    [string[]],
    "view"
  >;

  isAllocated: TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [boolean],
    "view"
  >;

  networkRiskScore: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAVS: TypedContractMethod<
    [avsId: BytesLike, name: string, tvl: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerValidator: TypedContractMethod<
    [validatorId: BytesLike, stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  reportByzantine: TypedContractMethod<
    [avsId: BytesLike],
    [void],
    "nonpayable"
  >;

  totalNetworkStake: TypedContractMethod<[], [bigint], "view">;

  totalSlashedStake: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CASCADE_RISK_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CASCADE_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SLASH_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRIMARY_RISK_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allAvsIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allValidatorIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allocateValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "avsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deallocateValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSlashing"
  ): TypedContractMethod<
    [avsId: BytesLike, slashBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAVS"
  ): TypedContractMethod<
    [avsId: BytesLike],
    [
      [string, bigint, bigint, boolean, boolean, boolean] & {
        name: string;
        totalTVL: bigint;
        validatorCount: bigint;
        byzantine: boolean;
        cascadeRisk: boolean;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAVSValidators"
  ): TypedContractMethod<[avsId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllAvsIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllValidatorIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCascadeRisk"
  ): TypedContractMethod<[avsId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNetworkRiskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNetworkSnapshot"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _totalNetworkStake: bigint;
        _totalSlashedStake: bigint;
        _networkRiskScore: bigint;
        _validatorCount: bigint;
        _avsCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalStake: bigint;
        slashedStake: bigint;
        remainingStake: bigint;
        serviceCount: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorServices"
  ): TypedContractMethod<[validatorId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isAllocated"
  ): TypedContractMethod<
    [validatorId: BytesLike, avsId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "networkRiskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAVS"
  ): TypedContractMethod<
    [avsId: BytesLike, name: string, tvl: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike, stake: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportByzantine"
  ): TypedContractMethod<[avsId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalNetworkStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSlashedStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AVSFlaggedByzantine"
  ): TypedContractEvent<
    AVSFlaggedByzantineEvent.InputTuple,
    AVSFlaggedByzantineEvent.OutputTuple,
    AVSFlaggedByzantineEvent.OutputObject
  >;
  getEvent(
    key: "AVSRegistered"
  ): TypedContractEvent<
    AVSRegisteredEvent.InputTuple,
    AVSRegisteredEvent.OutputTuple,
    AVSRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CascadeRiskDetected"
  ): TypedContractEvent<
    CascadeRiskDetectedEvent.InputTuple,
    CascadeRiskDetectedEvent.OutputTuple,
    CascadeRiskDetectedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreUpdated"
  ): TypedContractEvent<
    RiskScoreUpdatedEvent.InputTuple,
    RiskScoreUpdatedEvent.OutputTuple,
    RiskScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorAllocated"
  ): TypedContractEvent<
    ValidatorAllocatedEvent.InputTuple,
    ValidatorAllocatedEvent.OutputTuple,
    ValidatorAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorDeallocated"
  ): TypedContractEvent<
    ValidatorDeallocatedEvent.InputTuple,
    ValidatorDeallocatedEvent.OutputTuple,
    ValidatorDeallocatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRegistered"
  ): TypedContractEvent<
    ValidatorRegisteredEvent.InputTuple,
    ValidatorRegisteredEvent.OutputTuple,
    ValidatorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorSlashed"
  ): TypedContractEvent<
    ValidatorSlashedEvent.InputTuple,
    ValidatorSlashedEvent.OutputTuple,
    ValidatorSlashedEvent.OutputObject
  >;

  filters: {
    "AVSFlaggedByzantine(bytes32,address,uint256)": TypedContractEvent<
      AVSFlaggedByzantineEvent.InputTuple,
      AVSFlaggedByzantineEvent.OutputTuple,
      AVSFlaggedByzantineEvent.OutputObject
    >;
    AVSFlaggedByzantine: TypedContractEvent<
      AVSFlaggedByzantineEvent.InputTuple,
      AVSFlaggedByzantineEvent.OutputTuple,
      AVSFlaggedByzantineEvent.OutputObject
    >;

    "AVSRegistered(bytes32,string,uint256)": TypedContractEvent<
      AVSRegisteredEvent.InputTuple,
      AVSRegisteredEvent.OutputTuple,
      AVSRegisteredEvent.OutputObject
    >;
    AVSRegistered: TypedContractEvent<
      AVSRegisteredEvent.InputTuple,
      AVSRegisteredEvent.OutputTuple,
      AVSRegisteredEvent.OutputObject
    >;

    "CascadeRiskDetected(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      CascadeRiskDetectedEvent.InputTuple,
      CascadeRiskDetectedEvent.OutputTuple,
      CascadeRiskDetectedEvent.OutputObject
    >;
    CascadeRiskDetected: TypedContractEvent<
      CascadeRiskDetectedEvent.InputTuple,
      CascadeRiskDetectedEvent.OutputTuple,
      CascadeRiskDetectedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RiskScoreUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;
    RiskScoreUpdated: TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;

    "ValidatorAllocated(bytes32,bytes32)": TypedContractEvent<
      ValidatorAllocatedEvent.InputTuple,
      ValidatorAllocatedEvent.OutputTuple,
      ValidatorAllocatedEvent.OutputObject
    >;
    ValidatorAllocated: TypedContractEvent<
      ValidatorAllocatedEvent.InputTuple,
      ValidatorAllocatedEvent.OutputTuple,
      ValidatorAllocatedEvent.OutputObject
    >;

    "ValidatorDeallocated(bytes32,bytes32)": TypedContractEvent<
      ValidatorDeallocatedEvent.InputTuple,
      ValidatorDeallocatedEvent.OutputTuple,
      ValidatorDeallocatedEvent.OutputObject
    >;
    ValidatorDeallocated: TypedContractEvent<
      ValidatorDeallocatedEvent.InputTuple,
      ValidatorDeallocatedEvent.OutputTuple,
      ValidatorDeallocatedEvent.OutputObject
    >;

    "ValidatorRegistered(bytes32,uint256)": TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;
    ValidatorRegistered: TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;

    "ValidatorSlashed(bytes32,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;
    ValidatorSlashed: TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;
  };
}
